# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='此用户')),
            ],
            options={
                'verbose_name': '第一次创建数据库的表哈哈',
            },
        ),
    ]
