# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liuheziliao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mianfei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='免费公开资料')),
                ('url', models.URLField(max_length=300, verbose_name='免费公开资料跳转')),
            ],
            options={
                'verbose_name': '免费公开资料',
            },
        ),
        migrations.CreateModel(
            name='mingzhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名站大流量合作区')),
                ('url', models.URLField(max_length=300, verbose_name='名站大流量合作站跳转')),
            ],
            options={
                'verbose_name': '名站大流量合作',
            },
        ),
        migrations.CreateModel(
            name='OneselfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='标题')),
                ('url', models.URLField(max_length=300, verbose_name='跳转的地址')),
            ],
            options={
                'verbose_name': '今晚免费精准资料',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='合作站标题')),
                ('url', models.URLField(max_length=300, verbose_name='合作站跳转地址')),
            ],
            options={
                'verbose_name': '推荐同盟合作站',
            },
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
