# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-10 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liuheziliao', '0004_auto_20180608_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexTopdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='首页上部广告位')),
                ('url', models.URLField(max_length=300, verbose_name='首页上部广告位置跳转地址')),
                ('_index_url', models.CharField(max_length=120, verbose_name='首页中自己的页面显示地址')),
                ('standby_index_url', models.CharField(max_length=120, verbose_name='备用页面显示地址')),
            ],
            options={
                'verbose_name': '首页最上部广告位',
                'verbose_name_plural': '首页最上部广告位',
            },
        ),
        migrations.AlterField(
            model_name='oneselfdata',
            name='name',
            field=models.CharField(max_length=120, verbose_name='资料标题'),
        ),
    ]
