# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liuheziliao', '0007_auto_20180610_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneselfdata',
            name='wechat_img_qr_code',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
